import { Metadata } from "next";
import { AnimateIn } from "@/components/ui/AnimateIn";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy policy for Piece Work Pro. Learn how we collect, use, store, and protect your personal data when you use our piece work tracking and payroll software.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <section className="bg-bg-dark py-20 lg:py-28">
        <div className="mx-auto max-w-3xl px-6 text-center lg:px-8">
          <AnimateIn>
            <h1 className="font-heading text-4xl text-white sm:text-5xl">
              Privacy Policy
            </h1>
          </AnimateIn>
          <AnimateIn delay={0.1}>
            <p className="mt-6 text-text-on-dark-muted">
              Last updated: November 08, 2024
            </p>
          </AnimateIn>
        </div>
      </section>

      <section className="bg-bg-default">
        <div className="mx-auto max-w-3xl px-6 py-20 lg:px-8 lg:py-28">
          <div className="prose prose-lg max-w-none prose-headings:font-heading prose-headings:text-text-primary prose-p:text-text-body prose-li:text-text-body prose-strong:text-text-primary">
            <h2>Introduction</h2>
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use, and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>

            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>
              Words with capitalized initial letters have meanings defined under
              the following conditions. The following definitions shall have the
              same meaning regardless of whether they appear in singular or in
              plural.
            </p>
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li>
                <strong>Account</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate</strong> means an entity that controls, is
                controlled by, or is under common control with a party, where
                &quot;control&quot; means ownership of 50% or more of the
                shares, equity interest, or other securities entitled to vote
                for election of directors or other managing authority.
              </li>
              <li>
                <strong>Application</strong> means Piece Work Pro, the software
                program provided by the Company.
              </li>
              <li>
                <strong>Company</strong> (referred to as either &quot;the
                Company,&quot; &quot;We,&quot; &quot;Us,&quot; or
                &quot;Our&quot; in this Agreement) refers to Piece Work Pro LLC,
                2785 W Seltice Way, Ste A, Post Falls, ID 83854.
              </li>
              <li>
                <strong>Country</strong> refers to Idaho, United States.
              </li>
              <li>
                <strong>Device</strong> means any device that can access the
                Service such as a computer, a cellphone, or a digital tablet.
              </li>
              <li>
                <strong>Personal Data</strong> is any information that relates to
                an identified or identifiable individual.
              </li>
              <li>
                <strong>Service</strong> refers to the Application.
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal
                person who processes the data on behalf of the Company.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself.
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the
                Service, or the company or other legal entity on behalf of which
                such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>
            <h4>Usage Data</h4>
            <p>
              Usage Data is collected automatically when using the Service.
              Usage Data may include information such as Your Device&apos;s
              Internet Protocol address (e.g., IP address), browser type,
              browser version, the pages of our Service that You visit, the time
              and date of Your visit, the time spent on those pages, unique
              device identifiers, and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile
              operating system, the type of mobile Internet browser You use,
              unique device identifiers, and other diagnostic data.
            </p>
            <h4>Information Collected While Using the Application</h4>
            <p>
              While using Our Application, in order to provide features of Our
              Application, We may collect, with Your prior permission:
            </p>
            <ul>
              <li>Information regarding your location</li>
              <li>
                Pictures and other information from your Device&apos;s camera
                and photo library
              </li>
            </ul>
            <p>
              We use this information to provide features of Our Service, to
              improve and customize Our Service. The information may be uploaded
              to the Company&apos;s servers and/or a Service Provider&apos;s
              server or it may be simply stored on Your Device. You can enable
              or disable access to this information at any time, through Your
              Device settings.
            </p>

            <h3>Collection, Use, and Retention of Face Data</h3>
            <p>
              Our app collects user profile photos, which may include facial
              features if the user chooses to upload or capture their face using
              the device&apos;s camera or gallery.
            </p>
            <p>
              <strong>Purpose:</strong> The use of face data is strictly limited
              to improving the user experience within the app.
            </p>
            <ul>
              <li>
                <strong>Account Identification:</strong> Profile photos help
                identify users within the app.
              </li>
              <li>
                <strong>Personalization:</strong> Displaying the user&apos;s
                profile photo provides a personalized experience.
              </li>
            </ul>
            <p>
              Our app does not analyze, process, or extract biometric data from
              profile photos. Profile photos are not shared with third parties.
              Photos are securely stored on our servers using AWS S3 encryption,
              with servers located in the United States. Photos are retained
              while the account is active and permanently deleted within 30 days
              of account deletion.
            </p>

            <h3>Collection, Use, and Retention of Location Data</h3>
            <p>
              Our app collects location data to enhance functionality, improve
              user experience, and provide location-based services. Location
              data is collected only when users are actively clocked in and
              engaged with work.
            </p>
            <p><strong>Uses of Location Data:</strong></p>
            <ul>
              <li>
                <strong>Clock-In Accuracy:</strong> Ensures users clock in to
                the correct jobs and prevents errors.
              </li>
              <li>
                <strong>Geofencing Features:</strong> Assists users
                transitioning between jobs and calculates efficiency rates.
              </li>
              <li>
                <strong>Travel Time Tracking:</strong> Tracks time spent
                traveling between geofenced locations.
              </li>
              <li>
                <strong>Team Coordination:</strong> Management can view
                real-time locations of clocked-in users to support project
                planning and resource allocation.
              </li>
            </ul>
            <p>
              Location data is only collected when users are clocked in. The app
              does not continuously track location in the background unless
              required for active work-related functionalities with user
              consent. Location data is securely stored on servers with advanced
              encryption, is never shared or sold to third parties, and is
              retained only for the duration necessary. Data is automatically
              deleted within 30 days once its purpose has been served.
            </p>

            <h3>Data Security and User Privacy</h3>
            <p>
              We prioritize user privacy and take robust measures to ensure the
              safety of all collected data. All user data is stored on secure
              servers with industry-standard encryption and access control. We
              do not share, sell, or disclose data to third parties for
              advertising, marketing, or other purposes. Users may revoke
              location access or camera/gallery access at any time through their
              Device settings.
            </p>

            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li>To provide and maintain our Service, including monitoring usage</li>
              <li>To manage Your Account and registration as a user</li>
              <li>For the performance of a contract for products, items, or services You have purchased</li>
              <li>To contact You regarding updates, informative communications, and security updates</li>
              <li>To provide You with news, special offers, and general information about similar goods and services, unless You have opted not to receive such information</li>
              <li>To manage Your requests to Us</li>
              <li>For business transfers: to evaluate or conduct a merger, divestiture, restructuring, or acquisition</li>
              <li>For data analysis, identifying usage trends, and improving our Service, products, marketing, and Your experience</li>
            </ul>

            <h2>Sharing Your Personal Information</h2>
            <p>We may share Your personal information in the following situations:</p>
            <ul>
              <li><strong>With Service Providers:</strong> To monitor and analyze Service use and to contact You</li>
              <li><strong>For business transfers:</strong> In connection with a merger, sale of assets, financing, or acquisition</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our Affiliates, in which case we will require those Affiliates to honor this Privacy Policy</li>
              <li><strong>With business partners:</strong> To offer You certain products, services, or promotions</li>
              <li><strong>With other users:</strong> When You share personal information or interact in public areas</li>
              <li><strong>With Your consent:</strong> For any other purpose with Your consent</li>
            </ul>

            <h2>Retention of Your Personal Data</h2>
            <p>
              The Company will retain Your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use Your Personal Data to the extent necessary to comply
              with our legal obligations, resolve disputes, and enforce our legal
              agreements and policies.
            </p>
            <p>
              Usage Data is generally retained for a shorter period of time,
              except when this data is used to strengthen the security or to
              improve the functionality of Our Service, or We are legally
              obligated to retain this data for longer time periods.
            </p>

            <h2>Transfer of Your Personal Data</h2>
            <p>
              Your information, including Personal Data, is processed at the
              Company&apos;s operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to and maintained on computers
              located outside of Your state, province, country, or other
              governmental jurisdiction where the data protection laws may
              differ.
            </p>
            <p>
              Your consent to this Privacy Policy followed by Your submission of
              such information represents Your agreement to that transfer. The
              Company will take all steps reasonably necessary to ensure that
              Your data is treated securely and in accordance with this Privacy
              Policy.
            </p>

            <h2>Delete Your Personal Data</h2>
            <p>
              You have the right to delete or request that We assist in deleting
              the Personal Data that We have collected about You. Our Service
              may give You the ability to delete certain information about You
              from within the Service. You may update, amend, or delete Your
              information at any time by signing in to Your Account and visiting
              the account settings section. You may also contact Us to request
              access to, correct, or delete any personal information that You
              have provided to Us.
            </p>

            <h2>Disclosure of Your Personal Data</h2>
            <h3>Business Transactions</h3>
            <p>
              If the Company is involved in a merger, acquisition, or asset
              sale, Your Personal Data may be transferred. We will provide
              notice before Your Personal Data is transferred and becomes
              subject to a different Privacy Policy.
            </p>
            <h3>Law Enforcement</h3>
            <p>
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities.
            </p>
            <h3>Other Legal Requirements</h3>
            <p>
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h2>Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage, is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </p>

            <h2>Children&apos;s Privacy</h2>
            <p>
              Our Service does not address anyone under the age of 13. We do
              not knowingly collect personally identifiable information from
              anyone under the age of 13. If You are a parent or guardian and
              You are aware that Your child has provided Us with Personal Data,
              please contact Us. If We become aware that We have collected
              Personal Data from anyone under the age of 13 without
              verification of parental consent, We take steps to remove that
              information from Our servers.
            </p>

            <h2>Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third-party link, You will be
              directed to that third party&apos;s site. We strongly advise You
              to review the Privacy Policy of every site You visit. We have no
              control over and assume no responsibility for the content, privacy
              policies, or practices of any third-party sites or services.
            </p>

            <h2>Changes to This Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page
              and via email or a prominent notice on Our Service, prior to the
              change becoming effective. The &quot;Last updated&quot; date at
              the top of this Privacy Policy will be updated accordingly. You
              are advised to review this Privacy Policy periodically for any
              changes.
            </p>

            <h2>Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <ul>
              <li>
                By email:{" "}
                <a href="mailto:support@pieceworkpro.com">
                  support@pieceworkpro.com
                </a>
              </li>
              <li>
                By visiting our contact page:{" "}
                <a href="https://www.pieceworkpro.com/contact">
                  pieceworkpro.com/contact
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
}
